### ISSUE TITLE
Custom Carrier

### ISSUE THREAD

**Issue by karneaud** [PurplShip/purplship-php-client#11]
Hello,

Can this be used for custom carrier or do they have to be registered with the service?

**Comment by DanH91** [comment]
Hey @karneaud,

Any custom carriers need to be registered with the service.

Meaning the carrier you wish to support needs to be integrated like as an extension in https://github.com/PurplShip/purplship

e.g: like those https://github.com/PurplShip/purplship/tree/main/extensions
