### ISSUE TITLE
Tracking Example Needed

### ISSUE THREAD

**Issue by s22-tech** [purplship/purplship-php-client#16]
Hello,

Would you be willing to provide an example on how to track a package?  I've hit a wall.  I modified your sample code as follows:

```
<?php

	require_once(__DIR__ . '/vendor/autoload.php');

  // Configure API key authorization: Token
	$purplship = new \Purplship\Purplship('YOUR_API_KEY', 'https://cloud.purplship.com');

	try {
		$result = $purplship->trackers->retrievesRequest('1Z1234567899999999');
		print_r($result);
	}
	catch (Exception $e) {
		echo 'Error when retrieving tracking info: ', $e->getMessage(), PHP_EOL;
	}
```
but I can't get it to return the status.  This is what it returns:
```
GuzzleHttp\Psr7\Request Object
(
    [method:GuzzleHttp\Psr7\Request:private] => GET
    [requestTarget:GuzzleHttp\Psr7\Request:private] => 
    [uri:GuzzleHttp\Psr7\Request:private] => GuzzleHttp\Psr7\Uri Object
        (
            [scheme:GuzzleHttp\Psr7\Uri:private] => https
            [userInfo:GuzzleHttp\Psr7\Uri:private] => 
            [host:GuzzleHttp\Psr7\Uri:private] => cloud.purplship.com
            [port:GuzzleHttp\Psr7\Uri:private] => 
            [path:GuzzleHttp\Psr7\Uri:private] => /v1/trackers/1Z1234567899999999
            [query:GuzzleHttp\Psr7\Uri:private] => 
            [fragment:GuzzleHttp\Psr7\Uri:private] => 
        )

    [headers:GuzzleHttp\Psr7\Request:private] => Array
        (
            [Host] => Array
                (
                    [0] => cloud.purplship.com
                )

            [User-Agent] => Array
                (
                    [0] => OpenAPI-Generator/1.0.0/PHP
                )

            [Accept] => Array
                (
                    [0] => application/json
                )

            [Content-Type] => Array
                (
                    [0] => application/json
                )

            [Authorization] => Array
                (
                    [0] => Token key_kj4k4gkjh4kjh4hg4hjjh4v
                )

        )

    [headerNames:GuzzleHttp\Psr7\Request:private] => Array
        (
            [user-agent] => User-Agent
            [accept] => Accept
            [content-type] => Content-Type
            [authorization] => Authorization
            [host] => Host
        )

    [protocol:GuzzleHttp\Psr7\Request:private] => 1.1
    [stream:GuzzleHttp\Psr7\Request:private] => 
)
```
Thank you.

**Comment by DanH91** [comment]
Hi @s22-tech,

Thanks for opening the issue we are about to release richer documentation to cover all supported methods/operation.
I tried tracking myself and discovered that the tracking statuses weren't up to date with the latest purplship server (2021.7). While that error has nothing to do with this issue. I recommend updating your PHP client to the latest patch I just released to avoid having another error.

That said here is how the `/v1/trackers` API works with the PHP client:

## Create a tracker

When you want to get a package tracking status that will auto-update and get you the latest status in the dashboard, via webhooks or any time to retrieve a tracker, you need to create a tracker at first.

the method is ` $purplship->trackers->create('CARRIER_NAME', 'TRACKING_NUMBER');`

e.g:
```
<?php
require_once(__DIR__ . '/vendor/autoload.php');

// Configure API key authorization: Token
$purplship = new \Purplship\Purplship('YOUR_API_KEY', 'https://cloud.purplship.com');

try {
    $result = $purplship->trackers->create('dhl_universal', '1239410034');
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling trackers->create: ', $e->getMessage(), PHP_EOL;
}

?>
```

## Retrieve an existing tracker

Before you can retrieve a tracker, it must have been created within the purplship server before. Only then, you can retrieve the latest tracking status by retrieving the tracker.

The method is ` $purplship->trackers->create('TRACKING_NUMBER');` 
or ` $purplship->trackers->create('TRACKER_ID');`

e.g:
```
<?php
try {
    $result = $purplship->trackers->retrieves('1239410034');
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling trackers->retrieves: ', $e->getMessage(), PHP_EOL;
}

?>
```

## List all trackers

Now if you are displaying all your trackers somewhere or need to filter through them, you can get the list of trackers.

The method is ` $purplship->trackers->list();`

e.g:
```
<?php
try {
    $result = $purplship->trackers->list();
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling trackers->list: ', $e->getMessage(), PHP_EOL;
}

?>
```

Let me know if you encounter any issues.

**Comment by s22-tech** [comment]
Perfect!  Thanks, Dan.

One question, though.  I ran all three sections of the code
```
$result = $purplship->trackers->create('ups', $tracking_number);
print_r($result);

$result = $purplship->trackers->retrieves($tracking_number);
print_r($result);

$result = $purplship->trackers->list();
print_r($result);
```
and they all printed pretty much the same information.  Why is that?  

It looks like we can get away with just running `$purplship->trackers->create` and parsing those results.  Or am I missing something?

**Comment by DanH91** [comment]
That's right if all you want is to get the tracking status of a tracking number,
`$purplship->trackers->create` is enough because if you are sending it for the first time it will create the tracker, the second time, it will just return what already exists.

```
$result = $purplship->trackers->list();
```
is supposed to return a list of trackers though. So if you try another one, you should get more than one.
