### ISSUE TITLE
Unable to track package with Canada Post

### ISSUE THREAD

**Issue by emerysteele** [PurplShip/purplship-php-client#4]
I setup the demo docker container + input my Canada Post api credentials into the admin portal.

Verified that I could get the list of carriers through purplship-php-client, with canadapost being returned as a possible carrier.
`Array ( [0] => PurplShip\Model\CarrierSettings Object ( [container:protected] => Array ( [id] => car_0398f1e898bb4f558cdac1851b6772ed [carrier_name] => canadapost [carrier_id] => canadapost [test] => ) ) ) `

But when I try to track a package, I get the following error:

`Exception when calling Tracking->fetch: [404] Client error: `GET http://******.com:8010/v1/proxy/tracking/canadapost/**************?test=` resulted in a `404 Not Found` response: {"error":{"message":"No configured carrier of type: canadapost"}} `

**Comment by DanH91** [comment]
Hi @emerysteele ,

Thanks for trying out PurplShip and taking the time to report this issue.

Could you please provide the versions of `purplship-server` as well as `purplship-php-client` you are using?


On the meantime, did you set the `canadapost` carrier `test` as true or false?

I'll try to reproduce it too.

Thanks

**Comment by DanH91** [comment]
Hey @emerysteele, There was a regression with `test` flag and it was overridden to `False` in the backend.
It has been fixed in https://github.com/PurplShip/purplship-server/releases/tag/v2020.8.1.

Also, the documentation has been rejuvenated if you want to take a look https://docs.purplship.com
